const onlyDealerName = [
    "website",
    "packAmount",
    "address",
    "state",
    "city",
    "uuid",
    "phone",
    "isActive",
    "createdDate",
    "isDeleted",
    "dealerZipCode",
    "alwaysAvailable",
    "chromeExportId",
    "crmEmail",
    "dealerURI",
    "escalationEmail",
    "escalationFirstName",
    "escalationLastName",
    "escalationPhone",
    "logo",
    "notes",
    "ownerEmail",
    "ownerFirstName",
    "ownerLastName",
    "ownerPhone",
    "retailMarkup",
    "updatedAt",
    "text_match_info",
    "best_field_score",
    "best_field_weight",
    "fields_matched",
    "score",
    "tokens_matched",
    "id",
    "generalManagerEmail",
    "generalManagerFirstName",
    "generalManagerLastName",
    "generalManagerPhoneNumber",
    "prequelURL",
    "tradeToolURL",
    "managerPhone",
    "oem"
];

export const dealerNameColumns = () => {
    return onlyDealerName;
};
