export default {
  name: 'dropdownField',
  title: 'Dropdown Field',
  type: 'string',
  options: {
    list: [
      {title: 'Red', value: '#FF0000'},
      {title: 'Cyan', value: '#00FFFF'},
      {title: 'Blue', value: '#4f20f5'},
      {title: 'Dark Blue', value: '#00008B'},
      {title: 'Light Blue', value: '#ADD8E6'},
      {title: 'Purple', value: '#800080'},
      {title: 'Yellow', value: '#FFFF00'},
      {title: 'Lime', value: '#00FF00'},
      {title: 'Magenta', value: '#FF00FF'},
      {title: 'Pink', value: '#e94b91'},
      {title: 'Silver', value: '#C0C0C0'},
      {title: 'Gray', value: '#808080'},
      {title: 'Black', value: '#000000'},
      {title: 'Orange', value: '#FFA500'},
      {title: 'Brown', value: '#A52A2A'},
      {title: 'Maroon', value: '#800000'},
      {title: 'Green', value: '#008000'},
      {title: 'Olive', value: '#808000'},
      {title: 'Aquamarine', value: '#7FFFD4'},
    ],
  },
}
